#  Template Go (Golang) build

#  This template allows you to validate your Go (Golang) code.
#  The workflow allows running tests, build and code linting on the default branch.

image: golang:1.15

pipelines:
  default:
    - parallel:
      - step:
          name: Test and Build
          script:
            - mkdir test-reports
            - go get -u github.com/jstemmer/go-junit-report
            - go test -run . -isProd=false -portWebServer=2024 -redisServer=192.168.0.17
      - step:
          name: Deploy to test
          deployment: test
          trigger: manual  # Uncomment to make this a manual deployment.
          script:
            - echo "Deploying to test environment"
      - step:
          name: Build code
          script:
            - go build .
